CREATE TABLE `programmer` (
  `id` bigint(20) NOT NULL,
  `member_id` bigint(20) DEFAULT NULL,
  `hobby` varchar(64) DEFAULT NULL,
  `open_source` varchar(255) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL,
  `student` varchar(64) DEFAULT NULL,
  `employment` varchar(255) DEFAULT NULL,
  `formal_education` varchar(255) DEFAULT NULL,
  `undergrad_major` varchar(255) DEFAULT NULL,
  `company_size` varchar(255) DEFAULT NULL,
  `dev_type` text,
  `years_coding` varchar(255) DEFAULT NULL,
  `years_coding_prof` varchar(255) DEFAULT NULL,
  `job_satisfaction` varchar(255) DEFAULT NULL,
  `career_satisfaction` varchar(255) DEFAULT NULL,
  `hope_five_years` varchar(255) DEFAULT NULL,
  `job_search_status` varchar(255) DEFAULT NULL,
  `last_new_job` varchar(255) DEFAULT NULL,
  `assess_job1` varchar(255) DEFAULT NULL,
  `assess_job2` varchar(255) DEFAULT NULL,
  `assess_job3` varchar(255) DEFAULT NULL,
  `assess_job4` varchar(255) DEFAULT NULL,
  `assess_job5` varchar(255) DEFAULT NULL,
  `assess_job6` varchar(255) DEFAULT NULL,
  `assess_job7` varchar(255) DEFAULT NULL,
  `assess_job8` varchar(255) DEFAULT NULL,
  `assess_job9` varchar(255) DEFAULT NULL,
  `assess_job10` varchar(255) DEFAULT NULL,
  `assess_benefits1` varchar(255) DEFAULT NULL,
  `assess_benefits2` varchar(255) DEFAULT NULL,
  `assess_benefits3` varchar(255) DEFAULT NULL,
  `assess_benefits4` varchar(255) DEFAULT NULL,
  `assess_benefits5` varchar(255) DEFAULT NULL,
  `assess_benefits6` varchar(255) DEFAULT NULL,
  `assess_benefits7` varchar(255) DEFAULT NULL,
  `assess_benefits8` varchar(255) DEFAULT NULL,
  `assess_benefits9` varchar(255) DEFAULT NULL,
  `assess_benefits10` varchar(255) DEFAULT NULL,
  `assess_benefits11` varchar(255) DEFAULT NULL,
  `job_contact_priorities1` varchar(255) DEFAULT NULL,
  `job_contact_priorities2` varchar(255) DEFAULT NULL,
  `job_contact_priorities3` varchar(255) DEFAULT NULL,
  `job_contact_priorities4` varchar(255) DEFAULT NULL,
  `job_contact_priorities5` varchar(255) DEFAULT NULL,
  `job_email_priorities1` varchar(255) DEFAULT NULL,
  `job_email_priorities2` varchar(255) DEFAULT NULL,
  `job_email_priorities3` varchar(255) DEFAULT NULL,
  `job_email_priorities4` varchar(255) DEFAULT NULL,
  `job_email_priorities5` varchar(255) DEFAULT NULL,
  `job_email_priorities6` varchar(255) DEFAULT NULL,
  `job_email_priorities7` varchar(255) DEFAULT NULL,
  `update_CV` varchar(255) DEFAULT NULL,
  `currency` varchar(255) DEFAULT NULL,
  `salary` varchar(255) DEFAULT NULL,
  `salary_type` varchar(255) DEFAULT NULL,
  `converted_salary` varchar(255) DEFAULT NULL,
  `currency_symbol` varchar(255) DEFAULT NULL,
  `communication_tools` text,
  `time_fully_productive` varchar(255) DEFAULT NULL,
  `education_types` text,
  `self_taught_types` text,
  `time_after_bootcamp` varchar(255) DEFAULT NULL,
  `hackathon_reasons` text,
  `agree_disagree1` varchar(255) DEFAULT NULL,
  `agree_disagree2` varchar(255) DEFAULT NULL,
  `agree_disagree3` varchar(255) DEFAULT NULL,
  `language_worked_with` text,
  `language_desire_next_year` text,
  `database_worked_with` text,
  `database_desire_next_year` text,
  `platform_worked_with` text,
  `platform_desire_next_year` text,
  `framework_workedWith` text,
  `framework_desireNextYear` text,
  `IDE` text,
  `operating_system` varchar(255) DEFAULT NULL,
  `number_monitors` varchar(255) DEFAULT NULL,
  `methodology` varchar(255) DEFAULT NULL,
  `version_control` varchar(255) DEFAULT NULL,
  `checkIn_code` text,
  `ad_blocker` text,
  `ad_blocker_disable` text,
  `ad_blocker_reasons` text,
  `ads_agree_disagree1` text,
  `ads_agree_disagree2` text,
  `ads_agree_disagree3` text,
  `ads_actions` text,
  `ads_priorities1` text,
  `ads_priorities2` text,
  `ads_priorities3` text,
  `ads_priorities4` text,
  `ads_priorities5` text,
  `ads_priorities6` text,
  `ads_priorities7` text,
  `ai_dangerous` text,
  `ai_interesting` text,
  `ai_responsible` text,
  `ai_future` text,
  `ethics_choice` text,
  `ethics_report` text,
  `ethics_responsible` text,
  `ethicalImplications` text,
  `stack_overflow_recommend` text,
  `stack_overflow_visit` text,
  `stack_overflow_has_account` text,
  `stack_overflow_participate` text,
  `stack_overflow_jobs` text,
  `stack_overflow_dev_story` text,
  `stack_overflow_jobs_recommend` text,
  `stack_overflow_consider_member` text,
  `hypothetical_tools1` text,
  `hypothetical_tools2` text,
  `hypothetical_tools3` text,
  `hypothetical_tools4` text,
  `hypothetical_tools5` text,
  `wake_time` text,
  `hours_computer` text,
  `hours_outside` text,
  `skip_meals` text,
  `ergonomic_devices` text,
  `exercise` varchar(255) DEFAULT NULL,
  `gender` text,
  `sexual_orientation` text,
  `education_parents` text,
  `race_ethnicity` text,
  `dependents` text,
  `military_US` text,
  `survey_too_long` text,
  `survey_easy` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `member_id_UNIQUE` (`member_id`),
  KEY `hobby_index` (`hobby`),
  KEY `stdent_yearscoding_index` (`student`,`years_coding`),
  KEY `country_index` (`country`),
  KEY `exercise_index` (`exercise`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4