CHANGE MASTER TO MASTER_HOST='10.10.10.54', MASTER_PORT = 3306, MASTER_USER='replication_user', MASTER_PASSWORD='replication_pw', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=683;
GRANT REPLICATION SLAVE ON *.* TO 'replication_user'@'%';
 START SLAVE;
 SHOW SLAVE STATUS\G