INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
INSERT INTO station(name) VALUES SELECT COALESCE(max(id),0) FROM station
