FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY certs/fullchain.pem /etc/letsencrypt/live/tasklet1579.p-e.kr/fullchain.pem
COPY certs/privkey.pem /etc/letsencrypt/live/tasklet1579.p-e.kr/privkey.pem
